### ISSUE TITLE
Values in header will not be overwritten when specified in custom values file

### ISSUE THREAD

**Issue by IncredibleHannes** [google/oatts#17]
I was trying to generate tests for the 415 unsupported mediatype status code.
In order to specify an mediatype that is not supported I used a custom value file containing the following definition: 
`
"415": {
  "header": {
    "Accept": "undefined"
}`
The Accept field will be overwritten by the test generation. It works other keys that won't be automatically generated.

I already fixed this bug and I will contribute a PR.

**Comment by noahdietz** [comment]
Thanks for the fix! Much appreciated.
