### ISSUE TITLE
Body is not generated automatically 

### ISSUE THREAD

**Issue by arasabbasi** [google/oatts#21]
It seems like oatts expects the body "parameters" handled like in swagger 2.0 and not like in openapi 3.0

**Comment by noahdietz** [comment]
OAS 3 is not supported because sway does not parse 3.x. So yes oatts behavior is related to 2.0. Am I missing something?

**Comment by arasabbasi** [comment]
The issue is, that you expect body "parameters" as being supplied as parameters  which have defined "body" for the in attribute. But Body-Parameters are supplied as a separate attribute 'requestBody'

Like this:
```

      parameters:
        - in: path
          name: projectId
          schema:
            type: string
          required: true
          description: Project ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lexicon'
```

**Comment by noahdietz** [comment]
The `requestBody` field is an OAS 3.x [concept](https://swagger.io/docs/specification/describing-request-body/) and is not part of OAS 2.x. So this cannot be supported until oatts fully supports OAS 3.x. There is #6 to track that issue but it depends on sway to adopt 3.x before we can continue there. 

I'm going to close this in favor of the overall issue. Feel free to reopen this if I've you feel there is more to be done here.

**Comment by arasabbasi** [comment]
How does this work?
https://github.com/google/oatts/blob/master/lib/process.js#L275

**Comment by noahdietz** [comment]
If the parameter is marked as `in: body`, it is set as the body of the request, following the common practice [mentioned in the specification](https://github.com/OAI/OpenAPI-Specification/blob/f1852bd4bd89bf96ed929179f9f52cfa6621accb/versions/2.0.md#body-parameters) of it typically being an object schema

**Comment by arasabbasi** [comment]
Oh i understand now. This is a swagger refactored 2.0 suite. Ok...
