### ISSUE TITLE
Json body in request when testing POST

### ISSUE THREAD

**Issue by stigbd** [google/oatts#4]
This is probably possible, but I'm not able to figure out how. I am trying to have the generated test send a simple json request-body when testing a POST to my api. Like this:
```
        it('should respond 201 for "Null response"', function() {
            var response = request('post', 'http://localhost:8080/pets', {
                'body': {"name": "Jeffrey", "species": "dude"},
                'headers': {"Content-Type":"application/json","Accept":"application/json"},
                'time': true
            });
```
I have tried various ways in my customValuesFile, but none is working.

How should I go about to achieve this?

**Comment by stigbd** [comment]
I am sorry that I didn't study the openapi spec carefully enough. I have properly specified the post in the spec, and the body is included in the test. 
Thank you for a very useful module.

**Comment by noahdietz** [comment]
Hey @stigbd no need to apologize! Thanks for giving this module a try and opening an issue! Please feel free to ask questions here or hit me up on twitter @no_d_here

**Comment by RajeshAjjarapu** [comment]
Hello Noah and others. I am using oats and its pretty helpful.  I want to understand how do I come up with customvaluesfile or provide custom values so I can get the query params or request body gets updated when the test cases are generated. I did refer custom values.json but I did not understand. Any help please?
