### ISSUE TITLE
Empty request body for openapi 3.0 specs 

### ISSUE THREAD

**Issue by TobiG77** [google/oatts#5]
Hi,

I've been attempted to use oatts in a project to generate high level tests for an API with an openapi-3.0 specification. From reading the handlebar templates and running the test cases it appears there is support to populate a request body using an openapi spec (see attached)

Though the generated test (see below) does not contain the body parameter (please note, I've used customValues already to set the bearer token successfully) 

```
describe('tests for /example', function() {
    describe('tests for post', function() {
        it('should respond 201 for "Object created"', function() {
            var response = request('post', 'http://localhost:5000/example', { 
                'time': true
            });

            expect(response).to.have.status(201)
            return chakram.wait();
        });    
    });
});

```

Can you please advise whether this should be possible? Alternatively I'm prepared to dig in and add the functionality.

[example-spec.yaml.txt](https://github.com/google/oatts/files/2168879/example-spec.yaml.txt)

**Comment by noahdietz** [comment]
Hi @TobiG77 thanks for using this module and opening an issue!

This module is built using [sway](github.com/apigee-127/sway), which does the spec parsing and enables its traversal. Right now, sway doesn't support version 3.x.x of the OAS. That is a work in progress. 

So at the moment, I'm sorry to say that this module cannot support 3.x.x OAS documents.

**Comment by noahdietz** [comment]
I am going to close this issue in favor of another, more general v3 support oriented issue #6 

If you have any more comments or feel as though this was not sufficient, please reopen or just reply here! Thanks again for using `oatts`.
